-- =========================
-- DATA_KARYAWAN
-- =========================
CREATE TABLE IF NOT EXISTS DATA_KARYAWAN (
    KODE_NIK TEXT PRIMARY KEY,
    ID_AR TEXT,
    NAMA_AR TEXT NOT NULL,
    JABATAN TEXT,
    KODE_JABATAN TEXT,
    STATUS TEXT DEFAULT 'AKTIF',
    FOTO_ID TEXT
);

-- =========================
-- DATA_AKUN
-- =========================
CREATE TABLE IF NOT EXISTS DATA_AKUN (
    KODE_NIK TEXT PRIMARY KEY,
    NAMA_LENGKAP TEXT,
    ROLE TEXT,
    PASSWORD TEXT,
    STATUS TEXT DEFAULT 'AKTIF',
    LOG_INPUT TEXT
);

-- =========================
-- DATA_MONITORING_PERUSAHAAN
-- =========================
CREATE TABLE IF NOT EXISTS DATA_MONITORING_PERUSAHAAN (
    NPP TEXT PRIMARY KEY,
    NAMA_PRS TEXT,
    KEP_AWAL TEXT,
    KEP_JP TEXT,
    BLTH_NA TEXT,
    SKALA_USAHA TEXT,
    PROGRAM TEXT,
    TK_AKTIF INTEGER DEFAULT 0,
    TOTAL_IURAN REAL DEFAULT 0,
    ITW TEXT,
    KODE_NIK TEXT,
    GRUP TEXT,
    LOG_INPUT TEXT
);

-- =========================
-- DATA_MONITORING_JAKON
-- =========================
CREATE TABLE IF NOT EXISTS DATA_MONITORING_JAKON (
    NO_PROYEK TEXT PRIMARY KEY,
    NAMA_PROYEK TEXT,
    NPP_PELAKSANA TEXT,
    NAMA_PELAKSANA TEXT,
    MASA_PROYEK TEXT,
    NILAI_PROYEK REAL DEFAULT 0,
    NILAI_IURAN REAL DEFAULT 0,
    TGL_BAYAR TEXT,
    KODE_NIK TEXT,
    LOG_INPUT TEXT
);

-- =========================
-- DATA_TARGET_SETUP_AR
-- =========================
CREATE TABLE IF NOT EXISTS DATA_TARGET_SETUP_AR (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    KODE_NIK TEXT,
    BLN TEXT,
    THN TEXT,
    TARGET_IURAN_PU_BLN REAL DEFAULT 0,
    TARGET_IURAN_BPU_BLN REAL DEFAULT 0,
    TARGET_TK_BLN INTEGER DEFAULT 0,
    TARGET_PRS_BLN INTEGER DEFAULT 0,
    TARGET_IURAN_JAKON_BLN REAL DEFAULT 0,
    LOG_INPUT TEXT
);

-- =========================
-- DATA_MONITORING_IURAN_PU
-- =========================
CREATE TABLE IF NOT EXISTS DATA_MONITORING_IURAN_PU (
    KODE_NIK TEXT,
    NPP TEXT PRIMARY KEY,
    NAMA_PRS TEXT,
    TGL_REKON TEXT,
    IURAN_JHT INTEGER DEFAULT 0,
    IURAN_JKK INTEGER DEFAULT 0,
    IURAN_JKM INTEGER DEFAULT 0,
    IURAN_JP INTEGER DEFAULT 0,
    TOTAL_IURAN INTEGER DEFAULT 0,
    KODE_MINGGU TEXT,
    BLN TEXT,
    TAHUN TEXT,
    LOG_INPUT TEXT
);

-- =========================
-- DATA_MONITORING_IURAN_BPU
-- =========================
CREATE TABLE IF NOT EXISTS DATA_MONITORING_IURAN_PU_BARU (
    KODE_NIK TEXT,
    NPW TEXT PRIMARY KEY,
    NAMA_WADAH TEXT,
    TGL_REKON TEXT,
    IURAN_JHT INTEGER DEFAULT 0,
    IURAN_JKK INTEGER DEFAULT 0,
    IURAN_JKM INTEGER DEFAULT 0,
    IURAN_JP INTEGER DEFAULT 0,
    TOTAL_IURAN INTEGER DEFAULT 0,
    KODE_MINGGU TEXT,
    BLN TEXT,
    TAHUN TEXT,
    LOG_INPUT TEXT
);

-- =========================
-- HISTORY TK
-- =========================
CREATE TABLE IF NOT EXISTS DATA_TK_PU_HISTORY (
    KODE_NIK TEXT,
    TOTAL_TK_PU INTEGER DEFAULT 0,
    KODE_MINGGU TEXT,
    BLN TEXT,
    TAHUN TEXT,
    LOG_INPUT TEXT
);

CREATE TABLE IF NOT EXISTS DATA_TK_BPU_HISTORY (
    KODE_NIK TEXT,
    TOTAL_TK_BPU INTEGER DEFAULT 0,
    KODE_MINGGU TEXT,
    BLN TEXT,
    TAHUN TEXT,
    LOG_INPUT TEXT
);

CREATE TABLE IF NOT EXISTS DATA_TK_JAKON_HISTORY (
    KODE_NIK TEXT,
    TOTAL_TK_JAKON INTEGER DEFAULT 0,
    KODE_MINGGU TEXT,
    BLN TEXT,
    TAHUN TEXT,
    LOG_INPUT TEXT
);

-- =========================
-- TARGET KANTOR
-- =========================
CREATE TABLE IF NOT EXISTS DATA_TARGET_SETUP_KANTOR (
   KODE_KTR TEXT,
   TARGET_IUR_PU_BLN INTEGER DEFAULT 0,
   TARGET_IUR_BPU_BLN INTEGER DEFAULT 0,
   TARGET_IUR_JAKON_BLN INTEGER DEFAULT 0,
   TARGET_TK_PU_BLN INTEGER DEFAULT 0,
   TARGET_TK_BPU_BLN INTEGER DEFAULT 0,
   TARGET_TK_JAKON_BLN INTEGER DEFAULT 0,
   TARGET_PRS_PU_BLN INTEGER DEFAULT 0,
   TARGET_PRS_BPU_BLN INTEGER DEFAULT 0,
   TARGET_PRS_JAKON_BLN INTEGER DEFAULT 0,
   LOG_INPUT TEXT
);

-- =========================
-- IURAN JAKON HISTORY
-- =========================
CREATE TABLE IF NOT EXISTS DATA_IURAN_JAKON_HISTORY (
    KODE_NIK TEXT,
    TOTAL_PRS INTEGER DEFAULT 0,
    IURAN_JHT INTEGER DEFAULT 0,
    IURAN_JKK INTEGER DEFAULT 0,
    IURAN_JKM INTEGER DEFAULT 0,
    IURAN_JP INTEGER DEFAULT 0,
    TOTAL_IURAN INTEGER DEFAULT 0,
    KODE_MINGGU TEXT,
    BLN TEXT,
    TAHUN TEXT,
    LOG_INPUT TEXT
);

-- =========================
-- PERINGKAT
-- =========================
CREATE TABLE IF NOT EXISTS DATA_PERINGKAT_HISTORY (
    KODE_NIK TEXT,
    JML_IUR INTEGER DEFAULT 0,
    JML_PRS INTEGER DEFAULT 0,
    JML_TK INTEGER DEFAULT 0,
    POIN INTEGER DEFAULT 0,
    RANK INTEGER DEFAULT 0,
    KODE_MINGGU TEXT,
    BLN TEXT,
    TAHUN TEXT,
    LOG_INPUT TEXT
);

-- =========================
-- LOG UPLOAD
-- =========================
CREATE TABLE IF NOT EXISTS DATA_LOG_UPLOAD (
    KODE_MINGGU TEXT,
    BLN TEXT,
    TAHUN TEXT,
    TOTAL_IUR_PU INTEGER DEFAULT 0,
    TOTAL_IUR_BPU INTEGER DEFAULT 0,
    TOTAL_IUR_JAKON INTEGER DEFAULT 0,
    TOTAL_TK_PU INTEGER DEFAULT 0,
    TOTAL_TK_BPU INTEGER DEFAULT 0,
    TOTAL_TK_JAKON INTEGER DEFAULT 0,
    TOTAL_PRS_PU INTEGER DEFAULT 0,
    TOTAL_PRS_BPU INTEGER DEFAULT 0,
    TOTAL_PRS_JAKON INTEGER DEFAULT 0,
    ITW_IBB TEXT,
    LOG_INPUT TEXT
);